from selenium.webdriver.common.by import By

class Main_Locator:
    LOGO_YANDEX = (By.CSS_SELECTOR, "a.Header_LogoYandex__3TSOI")
    DZEN_FIND = (By.XPATH,".//a[contains(@class, 'dzen-layout--desktop-base-header__logoLink-2h') and contains(@aria-label, 'Логотип Бренда')]")
    POPUP_BROWSER_CLOSE = (By.XPATH, ".//span[@aria-label = 'Закрыть']")
    LOGO_SCOOTER = (By.CSS_SELECTOR, "a.Header_LogoScooter__3lsAR")
    BUTTON_ORDER = (By.XPATH, "//button[contains(@class, 'Button_Button') and text()='Заказать']")
    ORDER_STATUS = (By.CLASS_NAME, "Header_Link__1TAG7")
    HEADER_SCOOTER = (By.CLASS_NAME, "Home_Header__iJKdX")
    BIG_BUTTON_ORDER = (By.XPATH, "//div[@class = 'Home_FinishButton__1_cWm']/button[contains(text(), 'Заказать')]")
    BACK_SCOOTER_TEXT = (By.XPATH, ".//div[@class = 'Home_Status__YkfmH' and text() = 'Курьер забирает самокат']")
    COOKIE_BUTTON = (By.XPATH, ".//button[@id = 'rcc-confirm-button']")
        
class Main_Page_Locator:    
    FAQ_QUESTION_PRICE = (By.ID, "accordion__heading-0")
    FAQ_ANSWER_PRICE = (By.XPATH, ".//div[(@class = 'accordion__panel' and @aria-labelledby='accordion__heading-0')]")
    FAQ_QUESTION_SEVERAL_SCOOTERS = (By.ID, "accordion__heading-1")
    FAQ_ANSWER_SEVERAL_SCOOTERS = (By.XPATH, ".//div[(@class = 'accordion__panel' and @aria-labelledby='accordion__heading-1')]")
    FAQ_QUESTION_TIME = (By.ID, "accordion__heading-2")
    FAQ_ANSWER_TIME = (By.XPATH, ".//div[(@class = 'accordion__panel' and @aria-labelledby='accordion__heading-2')]")
    FAQ_QUESTION_ORDER_TODAY = (By.ID, "accordion__heading-3")
    FAQ_ANSWER_ORDER_TODAY = (By.XPATH, ".//div[(@class = 'accordion__panel' and @aria-labelledby='accordion__heading-3')]")
    FAQ_QUESTION_EXTEND_RETURN = (By.ID, "accordion__heading-4")
    FAQ_ANSWER_EXTEND_RETURN = (By.XPATH, ".//div[(@class = 'accordion__panel' and @aria-labelledby='accordion__heading-4')]")
    FAQ_QUESTION_CHARGE = (By.ID, "accordion__heading-5")
    FAQ_ANSWER_CHARGE = (By.XPATH, ".//div[(@class = 'accordion__panel' and @aria-labelledby='accordion__heading-5')]")
    FAQ_QUESTION_CANCEL_ORDER = (By.ID, "accordion__heading-6")
    FAQ_ANSWER_CANCEL_ORDER = (By.XPATH, ".//div[(@class = 'accordion__panel' and @aria-labelledby='accordion__heading-6')]")
    FAQ_QUESTION_MKAD = (By.ID, "accordion__heading-7")
    FAQ_ANSWER_MKAD = (By.XPATH, ".//div[(@class = 'accordion__panel' and @aria-labelledby='accordion__heading-7')]")

class Order_Page_locator:
    WHO_IS_SCOOTER_TEXT = (By.CLASS_NAME, "Order_Header__BZXOb")
    NAME_FIELD = (By.XPATH, ".//input[contains(@placeholder, 'Имя')]")
    LAST_NAME_FIELD = (By.XPATH, ".//input[contains(@placeholder, 'Фамилия')]")
    ADRESS_FIELD = (By.XPATH, ".//input[contains(@placeholder, 'Адрес')]")
    METRO_FIELD = (By.CLASS_NAME, "select-search__input")
    CHOICE_METRO_BUTTON = (By.XPATH, ".//button[@value = '{}']")  
    PHONE_FIELD = (By.XPATH, ".//input[contains(@placeholder, 'Телефон')]")
    NEXT_BUTTON = (By.XPATH, ".//button[contains(@class, 'Button_Middle__1CSJM') and text() = 'Далее']") 
    DATE_FIELD = (By.XPATH, ".//div[@class = 'react-datepicker__input-container']/input[contains(@placeholder, 'Когда')]")  
    RENTAL_TIME_FEILD = (By.XPATH, ".//span[@class = 'Dropdown-arrow']")
    CHOICE_RENTAL_TIME_BUTTON = (By.XPATH, ".//div[@class = 'Dropdown-menu']/div[contains(text(),'{}')]")
    CHOICE_COLOR_SCOOTER_BLACK = (By.ID, 'black')
    CHOICE_COLOR_SCOOTER_GREY = (By.ID, 'grey')
    COMMENTS_FIELD = (By.XPATH, ".//input[contains(@placeholder, 'Комментарий')]")
    ORDER_BUTTON = (By.XPATH, ".//button[contains(@class, 'Button_Middle__1CSJM') and text() = 'Заказать']")
    BACK_BUTTON = (By.XPATH, ".//button[contains(@class, 'Button_Inverted__3IF-i')]") 
    POPUP_QUESTION_ORDER = (By.CLASS_NAME, 'Order_ModalHeader__3FDaJ')
    BUTTON_ORDER_YES = (By.XPATH, ".//button[contains(@class, 'Button_Middle__1CSJM') and text() = 'Да']")
    BUTTON_ORDER_NO = (By.XPATH, ".//button[contains(@class, 'Button_Middle__1CSJM') and text() = 'Нет']")
    ORDER_PLACED_TEXT = (By.XPATH, "//div[contains(@class, 'Order_ModalHeader') and contains(text(), 'Заказ оформлен')]")
    BUTTON_STATUS = (By.XPATH, ".//button[contains(@class, 'Button_Middle__1CSJM') and text() = 'Посмотреть статус']")

